<?xml version="1.0" encoding="utf-8"?>
<Database Name="ScoreKeeper" Class="ScoreKeeperDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=USER-PC;Initial Catalog=ScoreKeeper;Integrated Security=True" SettingsObjectName="ScoreKeeper.Core.Properties.Settings" SettingsPropertyName="ScoreKeeperConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Game_GameEvent" Member="GameEvents" OtherKey="GameID" Type="GameEvent" />
      <Association Name="Game_Match" Member="Matches" OtherKey="GameID" Type="Match" />
    </Type>
  </Table>
  <Table Name="dbo.GameEvent" Member="GameEvents">
    <Type Name="GameEvent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreInterval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GameEvent_MatchEvent" Member="MatchEvents" OtherKey="GameEventID" Type="MatchEvent" />
      <Association Name="Game_GameEvent" Member="Game" ThisKey="GameID" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Player_MatchParticipant" Member="MatchParticipants" OtherKey="PlayerID" Type="MatchParticipant" />
      <Association Name="Player_MatchEvent" Member="MatchEvents" OtherKey="PlayerID" Type="MatchEvent" />
    </Type>
  </Table>
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MatchDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Match_MatchParticipant" Member="MatchParticipants" OtherKey="MatchID" Type="MatchParticipant" />
      <Association Name="Match_MatchEvent" Member="MatchEvents" OtherKey="MatchID" Type="MatchEvent" />
      <Association Name="Game_Match" Member="Game" ThisKey="GameID" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchParticipant" Member="MatchParticipants">
    <Type Name="MatchParticipant">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MatchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Match_MatchParticipant" Member="Match" ThisKey="MatchID" Type="Match" IsForeignKey="true" />
      <Association Name="Player_MatchParticipant" Member="Player" ThisKey="PlayerID" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchEvent" Member="MatchEvents">
    <Type Name="MatchEvent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameEventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MatchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GameEvent_MatchEvent" Member="GameEvent" ThisKey="GameEventID" Type="GameEvent" IsForeignKey="true" />
      <Association Name="Match_MatchEvent" Member="Match" ThisKey="MatchID" Type="Match" IsForeignKey="true" />
      <Association Name="Player_MatchEvent" Member="Player" ThisKey="PlayerID" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
</Database>